import React, { useState } from "react";
import axios from "axios";
import "./DailyReport.css";

function DailyReport({ user }) {
  const [date, setDate] = useState(new Date().toISOString().substring(0, 10));
  const [report, setReport] = useState(null);

  const runReport = async () => {
    try {
      const res = await axios.get(`http://localhost:5000/api/reports/daily?date=${date}`);
      setReport(res.data);
    } catch (err) {
      console.error("Error fetching report:", err);
      alert("❌ Failed to fetch report");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="report-container">
      <h2>Daily Report</h2>
      <div className="report-controls">
        <input type="date" value={date} onChange={(e) => setDate(e.target.value)} />
        <button onClick={runReport}>Run</button>
        {report && <button onClick={handlePrint}>        🖨 Print</button>}
      </div>

      {report && (
        <div className="invoice compact">
          {/* Header */}
          <div className="invoice-header">
            <h3>🛒 Supermarket POS</h3>
            <p><b>Date:</b> {report.date}</p>
            <p><b>Generated by:</b> {user.username} ({user.role})</p>
          </div>

          {/* Totals summary */}
          <div className="summary">
            <table className="summary-table">
              <thead>
                <tr>
                  <th>Total Invoices</th>
                  <th>Subtotal</th>
                  <th>Tax</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{report.totals.invoices}</td>
                  <td>${report.totals.subtotal.toFixed(2)}</td>
                  <td>${report.totals.tax.toFixed(2)}</td>
                  <td><b>${report.totals.total.toFixed(2)}</b></td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Invoices compact table */}
          <h4>Invoices Details</h4>
          {report.invoices.map((inv) => (
            <div key={inv._id} className="invoice-block">
              <p className="invoice-title">
                Invoice #{inv.invoiceNumber} | Cashier: {inv.cashier} | Total: ${inv.total.toFixed(2)}
              </p>
              <table className="compact-table">
                <thead>
                  <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Qty</th>
                    <th>Price</th>
                    <th>Total</th>
                  </tr>
                </thead>
                <tbody>
                  {inv.lines.map((line, idx) => (
                    <tr key={idx}>
                      <td>{line.name}</td>
                      <td>{line.productCategory || "N/A"}</td>
                      <td>{line.qty}</td>
                      <td>${line.price.toFixed(2)}</td>
                      <td>${(line.qty * line.price).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}

          {/* Category summary */}
          <h4>Sales by Category</h4>
          <table className="compact-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Qty Sold</th>
                <th>Sales</th>
              </tr>
            </thead>
            <tbody>
              {report.categories.map((cat) => (
                <tr key={cat._id}>
                  <td>{cat._id}</td>
                  <td>{cat.totalQty}</td>
                  <td>${cat.totalSales.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="invoice-footer">
            <p>✔ Professional Report generated automatically by POS system.</p>
          </div>
        </div>
      )}
    </div>
  );
}

export default DailyReport;
