import React, { useState } from "react";
import DailyReport from "./DailyReport";
import MonthlyReport from "./MonthlyReport";
import YearlyReport from "./YearlyReport";
import axios from "axios";
import {
  FaIndustry,
  FaChartPie,
  
  FaFileInvoiceDollar,
  FaPrint,
} from "react-icons/fa";
import "./Reports.css";

function Reports({ user }) {
  const [activeTab, setActiveTab] = useState("daily");

  const tabs = [
    { id: "daily", label: "📅 Daily" },
    { id: "monthly", label: "📈 Monthly" },
    { id: "yearly", label: "📊 Yearly" },
    { id: "range", label: "🗓️ Range" },
    { id: "supplier", label: "🏭 Supplier" },
  ];

  return (
    <div className="reports-wrapper">
      <div className="reports-header">
        <h2>Reports Dashboard</h2>
        <p className="subtitle">
          View detailed insights of your sales, profits, suppliers, and date-based reports.
        </p>
      </div>

      {/* Tabs */}
      <div className="tabs">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            className={`tab ${activeTab === tab.id ? "active" : ""}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Report Content */}
      <div className="report-content">
        {activeTab === "daily" && <DailyReport user={user} />}
        {activeTab === "monthly" && <MonthlyReport user={user} />}
        {activeTab === "yearly" && <YearlyReport user={user} />}
        {activeTab === "range" && <RangeReport user={user} />}
        {activeTab === "supplier" && <SupplierReport />}
      </div>
    </div>
  );
}

export default Reports;

/* -------------------- RANGE REPORT (in Monthly style) -------------------- */

function RangeReport({ user }) {
  const [start, setStart] = useState("");
  const [end, setEnd] = useState("");
  const [report, setReport] = useState(null);

  const runReport = async () => {
    if (!start || !end) {
      alert("Please select both start and end date");
      return;
    }
    try {
      const res = await axios.get(
        `http://localhost:5000/api/reports/range?start=${start}&end=${end}`
      );
      setReport(res.data);
    } catch (err) {
      console.error("Error fetching range report:", err);
      alert("❌ Failed to fetch range report");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="report-container">
      <h2 className="page-title">🗓️ Range Report</h2>

      <div className="report-controls">
        <input type="date" value={start} onChange={(e) => setStart(e.target.value)} />
        <input type="date" value={end} onChange={(e) => setEnd(e.target.value)} />
        <button onClick={runReport} className="btn-run">
          Run Report
        </button>
        {report && (
          <button onClick={handlePrint} className="btn-print">
            <FaPrint /> Print
          </button>
        )}
      </div>

      {report && (
        <div className="invoice professional">
          <div className="invoice-header">
            <FaFileInvoiceDollar className="icon" />
            <h3>Supermarket POS</h3>
            <p>
              <b>Range:</b> {start} → {end}
            </p>
            <p>
              <b>Generated by:</b> {user.username} ({user.role})
            </p>
          </div>

          {/* Summary */}
          <div className="card">
            <h4>💰 Overall Summary</h4>
            <table className="summary-table">
              <thead>
                <tr>
                  <th>Total Invoices</th>
                  <th>Subtotal</th>
                  <th>Tax</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{report.totals.invoices}</td>
                  <td>${report.totals.subtotal.toFixed(2)}</td>
                  <td>${report.totals.tax.toFixed(2)}</td>
                  <td className="highlight">${report.totals.total.toFixed(2)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Sales by Category */}
          <div className="card">
            <h4>
              <FaChartPie /> Sales by Category
            </h4>
            <table className="compact-table">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Qty Sold</th>
                  <th>Sales</th>
                </tr>
              </thead>
              <tbody>
                {report.categories.map((cat) => (
                  <tr key={cat._id}>
                    <td>{cat._id || "Uncategorized"}</td>
                    <td>{cat.totalQty}</td>
                    <td>${cat.totalSales.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Top Products */}
          <div className="card">
            <h4>🏆 Top Products</h4>
            <table className="compact-table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Qty</th>
                  <th>Sales</th>
                </tr>
              </thead>
              <tbody>
                {report.products.map((prod) => (
                  <tr key={prod._id}>
                    <td>{prod._id}</td>
                    <td>{prod.totalQty}</td>
                    <td>${prod.totalSales.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Cashier Summary */}
          {report.cashiers && report.cashiers.length > 0 && (
            <div className="card">
              <h4>👨‍💼 Sales by Cashier</h4>
              <table className="compact-table">
                <thead>
                  <tr>
                    <th>Cashier</th>
                    <th>Invoices</th>
                    <th>Total Sales</th>
                  </tr>
                </thead>
                <tbody>
                  {report.cashiers.map((c) => (
                    <tr key={c._id}>
                      <td>{c._id}</td>
                      <td>{c.invoices}</td>
                      <td>${c.totalSales.toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <div className="invoice-footer">
            <p>✔ Range Report generated by POS system</p>
          </div>
        </div>
      )}
    </div>
  );
}

/* -------------------- SUPPLIER REPORT -------------------- */

function SupplierReport() {
  const [suppliers, setSuppliers] = useState([]);
  const [products, setProducts] = useState([]);
  const [selectedSupplier, setSelectedSupplier] = useState("");
  const [filteredProducts, setFilteredProducts] = useState([]);

  React.useEffect(() => {
    const fetchData = async () => {
      try {
        const [supRes, prodRes] = await Promise.all([
          axios.get("http://localhost:5000/api/suppliers"),
          axios.get("http://localhost:5000/api/products"),
        ]);
        setSuppliers(supRes.data);
        setProducts(prodRes.data);
      } catch (err) {
        console.error("Error loading supplier report:", err);
      }
    };
    fetchData();
  }, []);

  React.useEffect(() => {
    if (selectedSupplier) {
      setFilteredProducts(products.filter((p) => p.supplierName === selectedSupplier));
    } else {
      setFilteredProducts([]);
    }
  }, [selectedSupplier, products]);

  const totals = filteredProducts.reduce(
    (acc, p) => {
      acc.count++;
      acc.totalQty += p.quantity || 0;
      acc.totalCost += (p.initialPrice || 0) * (p.quantity || 0);
      acc.totalSales += (p.productPrice || 0) * (p.quantity || 0);
      return acc;
    },
    { count: 0, totalQty: 0, totalCost: 0, totalSales: 0 }
  );
  const totalProfit = totals.totalSales - totals.totalCost;

  return (
    <div className="report-container">
      <h2 className="page-title">🏭 Supplier Report</h2>

      <div className="report-controls">
        <select
          className="form-select w-auto"
          value={selectedSupplier}
          onChange={(e) => setSelectedSupplier(e.target.value)}
        >
          <option value="">-- Choose Supplier --</option>
          {suppliers.map((s) => (
            <option key={s._id} value={s.name}>
              {s.name}
            </option>
          ))}
        </select>
      </div>

      {filteredProducts.length > 0 && (
        <div className="invoice professional">
          <div className="invoice-header">
            <FaIndustry className="icon" />
            <h3>{selectedSupplier} Supplier Report</h3>
          </div>

          <div className="card">
            <h4>📦 Products from Supplier</h4>
            <table className="compact-table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Initial Price</th>
                  <th>Sell Price</th>
                  <th>Qty</th>
                  <th>Profit/Unit</th>
                </tr>
              </thead>
              <tbody>
                {filteredProducts.map((p) => (
                  <tr key={p._id}>
                    <td>{p.productName}</td>
                    <td>${p.initialPrice?.toFixed(2) || "0.00"}</td>
                    <td>${p.productPrice?.toFixed(2) || "0.00"}</td>
                    <td>{p.quantity}</td>
                    <td className="text-success fw-bold">
                      ${(p.productPrice - p.initialPrice).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="card">
            <h4>💰 Totals</h4>
            <table className="summary-table">
              <tbody>
                <tr>
                  <td>Products</td>
                  <td>{totals.count}</td>
                </tr>
                <tr>
                  <td>Quantity</td>
                  <td>{totals.totalQty}</td>
                </tr>
                <tr>
                  <td>Cost</td>
                  <td>${totals.totalCost.toFixed(2)}</td>
                </tr>
                <tr>
                  <td>Sales</td>
                  <td>${totals.totalSales.toFixed(2)}</td>
                </tr>
                <tr>
                  <td>Profit</td>
                  <td className="highlight">${totalProfit.toFixed(2)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="invoice-footer">
            <p>✔ Supplier Report generated by POS system</p>
          </div>
        </div>
      )}
    </div>
  );
}
